---
- name: Restart odoo15
  service:
      name: odoo15
      state: restarted
      daemon_reload: yes 
      enabled: yes
- name: restart postgres
  ansible.builtin.systemd: 
    name: postgresql@12-main
    state: started
    enabled: yes
    daemon_reload: yes 