---
- include_tasks: installing_tools.yml
- include_tasks: odoo_user.yml
- include_tasks: wkhtml.yml
- include_tasks: postgresql.yml
- include_tasks: git.yml
- include_tasks: venv.yml
- include_tasks: odoo_setup.yml
- include_tasks: enabling_odoo_service.yml
  